import Head from 'next/head'
import About from '../components/About'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Work from '../components/Work'
import Project from '../components/Project'
import Contact from '../components/Contact'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sopagnarith SEAM | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Work />
      <Project />
      <Contact />
      <Footer />
    </div>
  )
}
